Issues/122 rwh crypto utils for pdq
highmed/highmed-dsf pull request #128
Opened 2020-09-23 10:42 UTC by wetret

- uses crypto utils library in pdq client
- reworks gitignore

closes #122 
closes #127

2020-10-06 14:30 UTC, hhund requested changes
create `dsf-bpe/dsf-bpe-server-jetty/docker/lib/README.md` file
remove existing `dsf-bpe/dsf-bpe-server-jetty/docker/lib/.gitignore` file
create `dsf-fhir/dsf-fhir-server-jetty/docker/lib/README.md` file
remove existing `dsf-fhir/dsf-fhir-server-jetty/docker/lib/.gitignore` file

for further remarks see line-by-line comments

2020-10-06 14:30 UTC, hhund commented on dsf-mpi/dsf-mpi-client-pdq/src/main/java/org/highmed/mpi/client/message/MessageHelper.java
>  		}
The qpd3counter variable does not need to be visible outside the loop. I would suggest using a `for (int`... loop.
```java
for (int qpd3counter = 0; qpd3counter < searchParameters.size(); qpd3counter++)
{
	QueryParameter searchParameter = searchParameters.get(qpd3counter);

	if (searchParameter.hasLocation())
	{
		terser.set(searchParameter.getLocation(), searchParameter.getValue());
	}
	else
	{
		terser.set("/QPD-3(" + qpd3counter + ")-1", searchParameter.getField());
		terser.set("/QPD-3(" + qpd3counter + ")-2", searchParameter.getValue());
	}
}
```

2020-10-06 14:30 UTC, hhund commented on dsf-tools/dsf-tools-test-data-generator/cert/ca/README.md
> +Will contain the test ca certificate and privkey generated in the build process
```suggestion
Will contain the Test CA certificate and private-key generated in the build process.

**Make sure to protect the CA private-key from third-party access if you have installed the Test CA certificate in your systems or browsers certificate store.**
```

2020-10-09 05:43 UTC, wetret commented
I made the requested changes.

2020-10-11 22:51 UTC, hhund approved these changes

2020-10-11 23:42 UTC, merged